name: Development

on:
  push:
    branches:
      - '*/*'
      - '!main'

jobs:
  prettier:
    uses: dascentral/reusable-workflows/.github/workflows/prettier.yml@main

  eslint:
    uses: dascentral/reusable-workflows/.github/workflows/eslint.yml@main
