name: Development

on:
  push:
    branches:
      - '*/*'
      - '!main'

jobs:
  prettier:
    uses: dascentral/reusable-workflows/.github/workflows/prettier.yml@main
    with:
      node-version: '20.11.1'
